### ISSUE TITLE
It doesn't look like a logarithmic scale.

### ISSUE THREAD

**Issue by KingaJelen** [libamtrack/web#107]
![przechwytywanie](https://user-images.githubusercontent.com/33397810/50164180-41202180-02e2-11e9-998b-52b1bb20f61c.PNG)

On left side - log scale, right - linear.
![przechwytywanie](https://user-images.githubusercontent.com/33397810/50164280-86445380-02e2-11e9-8cde-e19aec4940d8.PNG)

**Comment by adudzik** [comment]
It's because X scale is linear. Let's see example for 10 points:
X-linear:
![image](https://user-images.githubusercontent.com/23633694/50179230-c3224180-0306-11e9-8f62-c55aa10a8afd.png)

X-log:
![image](https://user-images.githubusercontent.com/23633694/50179276-e4832d80-0306-11e9-8b5b-5a49283622a6.png)

When you change Y scale we don't change X-values. When you set X scale to log we will order points in geometric serie. Is it ok, @grzanka?

**Comment by KingaJelen** [comment]
... y-scale is log and it doesn't look like log :) You should change notation 10^0, 10^-1 etc.

**Comment by grzanka** [comment]
See my answer here: https://github.com/libamtrack/web/issues/113#issuecomment-448587437

@adudzik ordering of points is correct. I suspect it is more the issue of formatting numbers.

**Comment by adudzik** [comment]
I am closing this, because it's logarithmic scale and we've got another issue for that (#113).
