### ISSUE TITLE
Empty space

### ISSUE THREAD

**Issue by KingaJelen** [libamtrack/web#112]
![przechwytywanie](https://user-images.githubusercontent.com/33397810/50165380-2602e100-02e5-11e9-972d-f616d9fbb29e.PNG)

**Comment by grzanka** [comment]
What do you mean by empty space ? What do you expect from the numbers that should be there on the axis ?

Can you make a log-log plot (of whatever) in some other tool (i.e. matplotlib/ seaborn), spanning more than one decade (i.e. 0.05...8 on X axis and 500...6000 on Y axis) and paste it here ?

Just to see what are your expectations.

**Comment by adudzik** [comment]
I think it's bug, because when you display values you can see that there are only values for 0 and 0.8.

After some research I found out, that it can be caused by fact that I try to calculate `log10(0)`. We can replace by e.g. `1e-12`.

**Comment by grzanka** [comment]
In general display of zero or negative values on plots with log-scale should be handled correctly. If possible to implement, such values could be simply skipped from plotting instead of being replaced with some small number.

**Comment by adudzik** [comment]
I aggree but in this case I use function which takes number of points, start and end of interval and returns a serie of points. So I think about replacement with small value, to be able to set the start of the interval. Another option is implementing another method for generating this points when serie has to start with 0.

**Comment by grzanka** [comment]
Which function you mean ? Some function from libamtrack or a function that generates series of the points based on user input ("start", "end", "how many") ?

If the second one then you are right. I thought you mean some function from libamtrack.

Instead of doing magic for user, in that case I'd show a warning message with text like:
 "logarithmic scale on X axis requested for invalid lower range value (zero). Rescaling to [a,b]. Please consider setting new value to lower range border.".

I'd assume new value of start as "end/1000" instead of 1e-12
